config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "pages#home", as: :home
  get "about", to: "pages#about", as: :about
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flour.rb
class Flour < ApplicationRecord
end

app/models/sourdough.rb
class Sourdough < ApplicationRecord
  has_one :starter
  has_many :flour
  has_one :water
end

app/models/starter.rb
class Starter < ApplicationRecord
  has_one :flour
  has_one :water
end

app/models/water.rb
class Water < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @navbar_left = true
  end

  def about
    @navbar_right = true
  end
end

app/controllers/sourdoughs_controller.rb
class SourdoughsController < ApplicationController
end

app/controllers/starters_controller.rb
class StartersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navbar_underline
    if @navbar_left
      'navbar-left'
    elsif @navbar_right
      'navbar-right'
    else
      ''
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Dough Mate" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# custom fonts - Switzer & Gambarino %>
    <link href="https://api.fontshare.com/v2/css?f[]=switzer@300,301,400,401&f[]=gambarino@400&display=swap" rel="stylesheet">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="main-container">
  <h1 class="h1-titles">About us</h1>
  <p class="about-p">Welcome to <span>Dough mate</span>—your personal guide to
  mastering the art of sourdough, one step at a time.</p>
  <p class="about-p">We know that making sourdough can feel like a complex and intimidating
  process. Between feeding your starter, keeping track of rise times, and
  understanding fermentation, it's easy to get overwhelmed. That's why we
  created <span>Dough mate</span>—a simple, intuitive app designed to take the
  guesswork out of sourdough baking.</p>
  <p class="about-p">Whether you're a first-time baker or looking to perfect your process,
  Dough mate  provides step-by-step guidance to help you create a healthy
  starter and bake delicious sourdough bread.</p>


  <div class="elliptical" id="eliptic-about">
    <%= link_to home_path do %>
      <p class="link-p">get started</p>
    <% end %>
  </div>

</div>

app/views/pages/home.html.erb
<div class="main-container">
  <h1 class="h1-home">Dough</h1>
  <div class="flex-row-container">
    <div class="elliptical" id="oval-home"></div>
    <h1 class="h1-home" id="h1-home">mate</h1>
  </div>

  <p class="home-p" id="home-intro">Step-by-step guidance for<br>perfect sourdough</p>
  <p class="home-p" id="home-q">Choose your journey!</p>

  <div class="home-links">
    <%= link_to "#", class: "home-btn" do %>
      <i class="fa fa-long-arrow-left arrow1" aria-hidden="true"></i>
      <p id="starter-p">STARTER</p>
    <% end %>
    <%= link_to "#", class: "home-btn" do %>
      <p id="sourdough-p">SOURDOUGH</p>
      <i class="fa fa-long-arrow-right arrow2" aria-hidden="true"></i>
    <% end %>
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-container">
  <%= link_to home_path do %>
    <p class="navbar-links">Home</p>
  <% end %>

  <%= link_to about_path do %>
   <p class="navbar-links">About</p>
  <% end %>
  <span class="<%= navbar_underline %> absolute bg-rust" id="navbar-underline"></span>
</div>